# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: fiber-mongo
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: fiber-mongo
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

#dockers:
##  - latest: true
#  - image_templates:
#    - 'yurikrupnik/fiber-mongo:{{ .Tag }}'
#  - build_flag_templates:
#    - "--platform=linux/amd64"
#  - tag_templates:
#      - '{{ .Tag }}'

release:
  # Default is empty.
  draft: true
  prerelease: auto
  name_template: "v{{ .Version }}"
#  disable: false
#  mode: append
  gitea:
    owner: yurikrupnik
    name: fiber-mongo
#  ids:
#    - foo
#    - bar

  header: |
    ## Some title ({{ .Date }})
    
    Welcome to this new release!
    
    # Footer template for the release body.
    # Defaults to empty.
  footer: |
    ## Thanks!
  
    Those were the changes on {{ .Tag }}!



dockers:
  - image_templates:
      - "yurikrupnik/fiber-mongo:{{ .Version }}-{{ .ProjectName }}"
      - "yurikrupnik/fiber-mongo:{{ .Tag }}-amd64"
      - "yurikrupnik/fiber-mongo:{{ .ProjectName }}-amd64"
#    use: docker
    use: buildx
    #    use: podamn # todo check how to make it work
    dockerfile: Dockerfile
#    build_flag_templates:
#      - "--platform=linux/amd64"
#      - "--platform=linux/arm64/v8"
#  - image_templates:
#      - "yurikrupnik/fiber-mongo:{{ .Version }}-arm64v8"
#    use: buildx
#    #    goarch: arm64
#    dockerfile: Dockerfile
#    build_flag_templates:
#      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: yurikrupnik/fiber-mongo:{{ .Version }}
    image_templates:
      - yurikrupnik/fiber-mongo:{{ .Version }}-amd64
      - yurikrupnik/fiber-mongo:{{ .Version }}-arm64v8