# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
env:
#  - FOO={{ .Env.FOOBAR }}
  - IMAGE_COPY={{ .Env.IMAGE }}
  - IMAGE={{ .Env.IMAGE }}
project_name: fiber-mongo
before:
  hooks:
    - go mod tidy
#    - echo $IMAGE_COPY
#    - echo ${IMAGE_COPY}
#    - echo $IMAGE
#    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    binary: fiber-mongo
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
#  name_template: "{{ incpatch .Version }}-next"
  name_template: "{{ .ProjectName }}_{{ .Version }}" # {{ .Os }}_{{ .Arch }}


changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

#dockers:
##  - latest: true
#  - image_templates:
##    - "yurikrupnik/{{ .ProjectName }}:{{ .Version }}"
#    - 'yurikrupnik/{{ .ProjectName }}:{{ .Tag }}'
#    - 'yurikrupnik/{{ .ProjectName }}:latest'
#  - build_flag_templates:
#    - "--platform=linux/amd64"
#  - tag_templates:
#      - '{{ .Tag }}'

release:
  # Default is empty.
  draft: true
  prerelease: auto
  name_template: "yurikrupnik/fiber-mongo:{{ .Version }}-{{ .ProjectName }}"
#  disable: false
  mode: append
  gitea:
    owner: yurikrupnik
    name: fiber-mongo
#  ids:
#    - foo
#    - bar

  header: |
    ## Some title ({{ .Date }})
    
    Welcome to this new release!
    
    # Footer template for the release body.
    # Defaults to empty.
  footer: |
    ## Thanks!
  
    Those were the changes on {{ .Tag }}!


dockers:
  -
    image_templates:
      - "yurikrupnik/bar:{{ .Version }}-amd64"
    use: buildx
    goarch: amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  -
    image_templates:
      - "yurikrupnik/bar:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64

    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
docker_manifests:
  -
    name_template: yurikrupnik/bar:{{ .Version }}
    image_templates:
      - yurikrupnik/bar:{{ .Version }}-amd64
      - yurikrupnik/bar:{{ .Version }}-arm64v8