apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiber-mongo
  labels:
    app: fiber-mongo
spec:
  replicas: 1
  template:
    metadata:
      name: fiber-mongo
      labels:
        app: fiber-mongo
    spec:
      containers:
        - name: fiber-mongo
          image: yurikrupnik/fiber-mongo:refs-pull-15-merge
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URI
              value: mongodb+srv://yurikrupnik:T4eXKj1RBI4VnszC@cluster0.rdmew.mongodb.net/

      restartPolicy: Always
  selector:
    matchLabels:
      app: fiber-mongo

