apiVersion: v1
kind: Service
metadata:
  name: fiber-mongo-service
  labels:
    run: fiber-mongo-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fiber-mongo
