# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more infsormation see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Basic golang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
#    runs-on: self-hosted
    strategy:
      matrix:
        go-version: [ 1.17.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
      - run: go test ./...
      - run: go build
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "bot"
#      - name: Bump version
#        uses: remorses/bump-version@js
#        with:
#          version_file: ./VERSION
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: prerelease
          preid: 'prc'
      - run: echo "$TAG"
      - run: cat package.json
      - run: env
      - name: Docker build
        run: docker build . -t yurikrupnik/fiber-mongo:${{ steps.vars.outputs.sha_short }}
      - name: Docker images
        run: docker images
#      - name: Run GoReleaser
#        uses: goreleaser/goreleaser-action@v3
#        with:
#          # either 'goreleaser' (default) or 'goreleaser-pro'
#          distribution: goreleaser
#          #          version: latestd
#          args: release --rm-dist
#        #          args: release --rm-dist
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Git tag and push
#        run: |
#          git tag -a v0.2.9 -m "third release"
#          git push --tags
#      - uses: rymndhng/release-on-push-action@v0.25.0
#        with:
#          bump_version_scheme: patch
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


