# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more infsormation see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Basic golang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
#    runs-on: self-hosted
    strategy:
      matrix:
        go-version: [ 1.17.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
#      - run: make release-dry
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      #      - id: 'auth'
      #        uses: 'google-github-actions/auth@v0'
      #        with:
      #          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
#      - name: Bump version and push tag
#        id: tag_version
#        uses: mathieudutour/github-tag-action@v6.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
#          version: latest
          args: build --rm-dist --snapshot
#          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "bot"
      - name: 'Automated Version Bump'
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: prerelease
      - name: echo "$TAG"
#      - name: Git tag and push
#        run: |
#          git tag -a v0.2.9 -m "third release"
#          git push --tags
#      - uses: rymndhng/release-on-push-action@v0.25.0
#        with:
#          bump_version_scheme: patch
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


