# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more infsormation see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Basic GOLANG CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
#    runs-on: self-hosted
    strategy:
      matrix:
        go-version: [ 1.6.x, 1.17.x, 1.18.x ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go version
