on:
  workflow_dispatch:
    inputs:
      command:
        description: 'command to run'
        required: true
        default: 'build'
      message:
        description: "Tag's message"
        required: true
        default: 'Default release'
      tags:
        description: 'Test scenario tags'
        default: 'latest'
        required: false
        options:
          - prerelease
          - patch
          - major
          - minor

jobs:
  build:

    runs-on: ubuntu-latest
    #    runs-on: self-hosted
    #    strategy:
    #      matrix:
    #        node-version: [ 16.x ]
    #        go-version: [ 1.18.x ]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v5
        name: Checkout [main]
        with:
          fetch-depth: 0
      - run: yarn install
      - uses: actions/setup-go@v5
        with:
          go-version: 1.25
      #          go-version: ${{ matrix.go-version }
#      - run: go version
#      - run: GOOS=linux GOARCH=amd64 yarn build
      - run: |
          echo ${{ github }}
          echo $GITHUB_CONTEXT
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name ${{ github.actor }}
      - name: Git tag and push
        run: |
          git tag -a v${{ github.event.inputs.tag }} -m ${{ github.event.inputs.message }}
          git push --tags